// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EFCoreDemo.Models
{
    public partial class ContosouniversityContext : DbContext
    {
        public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            var entites = this.ChangeTracker.Entries();
            foreach (var entry in entites)
            {
                if (entry.State == EntityState.Added || entry.State == EntityState.Modified)
                {
                    entry.CurrentValues.SetValues(new { DateModified = DateTime.Now });
                }
            }
            return base.SaveChangesAsync(cancellationToken);
        }
    }
}